name: Build a Docker image for amd64 and arm64, and publish it to a container registry

on:
  workflow_call:
    inputs:
      container_registry:
        description: "Docker container registry to authenticate with"
        type: string
        default: "ghcr.io"

      image_name:
        description: "Name to assign the built image"
        type: string
        default: ${{ github.repository }}

      dockerfile:
        description: "Dockerfile to build the image from"
        type: string
        default: "Dockerfile"

      tag_repo_with_version:
        description: "Flag for whether to tag the calling repo with the current version number (only applies if this is being called from the default branch)"
        type: boolean
        default: true

      docker_build_args:
        description: "Any build arguments to be passed to the Docker build action"
        type: string
        default: ""

    secrets:
      APT_SERVER_NAME:
        description: "Domain name of the apt server to authenticate with"
        required: true

      APT_SIGNING_PUBKEY:
        description: "Public key of the apt server to be accessed"
        required: true

      APT_RETRIEVE_USER:
        description: "User to authenticate to the apt server with"
        required: true

      APT_RETRIEVE_TOKEN:
        description: "Token to authenticate to the apt server with"
        required: true

      DOCKER_BUILD_SECRETS:
        description: "Any secrets to be passed to the Docker build action"
        required: false

    outputs:
      image_tag:
        description: "Tag of the built image"
        value: ${{ jobs.build-and-push-image.outputs.digest }}

jobs:
  extract-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      PKG_VERSION: ${{ steps.extract-version.outputs.PKG_VERSION }} 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version number
        working-directory: .
        id: extract-version
        run: |
          echo "PKG_VERSION=$(cat version)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Create version tag
        if: |
          inputs.tag_repo_with_version &&
          github.ref_name == github.event.repository.default_branch
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${{steps.extract-version.outputs.PKG_VERSION }}`,
              sha: context.sha
            })
            
  build-and-push-image:
    uses: UMRoboticsTeam/github-builder/.github/workflows/build.yml@temp-change-certificate-identity
    needs: extract-version
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    with:
      output: image
      meta-images: ${{ inputs.container_registry }}/${{ inputs.image_name }}
      meta-tags: |
        type=raw,value=v${{ needs.extract-version.outputs.PKG_VERSION }},priority=1000,enable={{is_default_branch}}
        # Since default branch is main not master, we need to override what latest looks for
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=sha
      push: true
      sign: true
      set-meta-labels: true
      platforms: linux/amd64,linux/arm64
      runner: |
        default=ubuntu-latest
        linux/amd64=ubuntu-latest
        linux/arm64=ubuntu-24.04-arm
      distribute: true
      fail-fast: true
      artifact-name: random_name_which_doesnt_conflict_with_secrets
      context: .
      file: ./${{ inputs.dockerfile }}
      build-args: |
            ${{ inputs.docker_build_args }}
    secrets:
      registry-auths: |
        - registry: ${{ inputs.container_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      build-secrets: |
        "apt_pubkey=${{ secrets.APT_SIGNING_PUBKEY }}"
        "apt_auth_conf=machine ${{ secrets.APT_SERVER_NAME }} login ${{ secrets.APT_RETRIEVE_USER }}  password ${{ secrets.APT_RETRIEVE_TOKEN }}"
        ${{ secrets.DOCKER_BUILD_SECRETS }}